ENDPOINT_SCHEMAS: dict[str, list[str]] = {
    "visao_geral": [
        "data_extracao",
        "data_referencia",
        "publicacoes_coletadas",
        "variacao_publicacoes_pct",
        "total_usuarios",
        "variacao_usuarios_pct",
        "alcance_potencial",
        "variacao_alcance_pct",
        "indice_sentimento",
        "variacao_sentimento_pts",
        "sentimento_negativo_qtd",
        "sentimento_neutro_qtd",
        "sentimento_positivo_qtd",
        "canal_twitter",
        "canal_facebook",
        "canal_noticias",
        "canal_instagram",
        "canal_youtube",
        "canal_blogs",
    ],
    "sentimento_grupos": [
        "data_referencia",
        "marca",
        "canal",
        "qtd_positivo",
        "qtd_neutro",
        "qtd_negativo",
        "total_mencoes",
        "pct_positivo",
        "pct_neutro",
        "pct_negativo",
        "saude_marca_score",
    ],
    "sentimento_temas": [
        "data_referencia",
        "tema",
        "canal",
        "qtd_positivo",
        "qtd_neutro",
        "qtd_negativo",
        "total_mencoes",
        "pct_positivo",
        "pct_neutro",
        "pct_negativo",
    ],
    "linechart": [
        "data_referencia",
        "total_publicacoes",
        "hora",
    ],
    "publicacoes": [
        "data_referencia",
        "data_publicacao",
        "data_extracao",
        "marca",
        "todas_marcas",
        "sentimento",
        "sentimento_num",
        "post_url",
        "texto",
        "canal",
        "interacoes",
        "curtidas",
        "comentarios",
        "compartilhamentos",
        "temas",
        "tags",
        "pid",
        "seguidores_autor",
        "score_aaa",
        "nivel_criticidade",
    ],
    "ranking_evolutivo": [
        "data_referencia",
        "marca",
        "posicao_ranking",
        "total_mencoes",
        "descritores",
    ],
}

DEDUP_KEYS: dict[str, list[str]] = {
    "publicacoes": ["pid"],
}

COLUNAS_DATA: dict[str, list[str]] = {
    "visao_geral": ["data_referencia", "data_extracao"],
    "sentimento_grupos": ["data_referencia"],
    "sentimento_temas": ["data_referencia"],
    "linechart": ["data_referencia"],
    "publicacoes": ["data_referencia", "data_publicacao", "data_extracao"],
    "ranking_evolutivo": ["data_referencia"],
}

DEFAULTS_BY_TYPE: dict[type, object] = {
    int: 0,
    float: 0.0,
    str: "",
}
